name: "Deploy codigoFacilito"

on:
  push: #Vamos a disparar este workflow cuando se haga un push 
    branches: ["main"] #un push sobre la rama main, se ejecute este workflow

jobs: 
  deploy-codigofacilito: #nombre del job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "generar binario"
      - run: echo "publicar version"
      - run: echo "publicar version master"

